---
apiVersion: v1
kind: Namespace
metadata:
  name: flask 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-content
  namespace: flask
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: netapp-cvs-perf-premium

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-demo
  template:
    metadata:
      labels:
        app: flask-demo
    spec:
      volumes:
      - name: flask-data
        persistentVolumeClaim:
           claimName: flask-content
      containers:
      - name: flask-demo
        image: pdavis39/flask-cnn-demo
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: flask-data
          mountPath: /app
       

---

apiVersion: v1
kind: Service
metadata:
  name: flask-lb
  namespace: flask
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      targetPort: 5000 #<port that the app listens on in apps or containers>
      port: 60000 #<port that the cloud load balancer listens on- you would access your app using "ip_add_lb:60000">
  selector:
    app: flask-demo
